all:
	echo Making ECalABSuppSum.
	(cd ECalABSuppSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppSum.

clean:
	(cd ECalABSuppSum        && make -is clean && cd ..)
	rm -f *~
