all:
	echo Making AngleBetweenHits.
	(cd AngleBetweenHits && make -is clean && make && make -is clean && cd ..)
	echo DONE: AngleBetweenHits.
	
	echo Making TrigBits.
	(cd TrigBits && make -is clean && make && make -is clean && cd ..)
	echo DONE: TrigBits.
	
	echo Making CsIPos.
	(cd CsIPos && make -is clean && make && make -is clean && cd ..)
	echo DONE: CsIPos.
	
	echo Making CsIPosSum.
	(cd CsIPosSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: CsIPosSum.
	
	echo Making Separator_TigressCsITTCalDiff.
	(cd TigressCsITTCalDiff && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_TigressCsITTCalDiff.
	
	echo Making Separator_TigressTTCalDiff.
	(cd TigressTTCalDiff && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_TigressTTCalDiff.
	
	echo Making Separator_TigressTTCalDiffFirstHit.
	(cd TigressTTCalDiffFirstHit && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_TigressTTCalDiffFirstHit.
	
	echo Making Separator_TigressTTCalDiffDropOutliers.
	(cd TigressTTCalDiffDropOutliers && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_TigressTTCalDiffDropOutliers.
	
	echo Making Separator_TigressTTCalDiffCentralValue.
	(cd TigressTTCalDiffCentralValue && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_TigressTTCalDiffCentralValue.
	
	echo Making Separator_TigressDropCore.
	(cd TigressDropCore && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_TigressDropCore.
	
	echo Making Separator_CsITTCalDiff.
	(cd CsITTCalDiff && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_CsITTCalDiff.
	
	echo Making Separator_CsITTCalDiffFirstHit.
	(cd CsITTCalDiffFirstHit && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_CsITTCalDiffFirstHit.
	
	echo Making Separator_CsITTCalDiffDropOutliers.
	(cd CsITTCalDiffDropOutliers && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_CsITTCalDiffDropOutliers.
	
	echo Making Separator_CsITTCalDiffCentralValue.
	(cd CsITTCalDiffCentralValue && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_CsITTCalDiffCentralValue.
	
	echo Making Separator_TigressCsITTCalDiffSAFE.
	(cd TigressCsITTCalDiffSAFE && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_TigressCsITTCalDiffSAFE.
	
	echo Making Separator_TigressCsITTCalFirstHitDiff.
	(cd TigressCsITTCalFirstHitDiff && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_TigressCsITTCalFirstHitDiff.
	
	echo Making Separator_TigressCsITTCalAnyHitDiff.
	(cd TigressCsITTCalAnyHitDiff && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_TigressCsITTCalAnyHitDiff.
	
	echo Making Separator_TigressCsITTCalFirstHitDiffCentralValue.
	(cd TigressCsITTCalFirstHitDiffCentralValue && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_TigressCsITTCalFirstHitDiffCentralValue.
	
	echo Making Separator_TigressCsITTCalDropOutliers.
	(cd TigressCsITTCalDropOutliers && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_TigressCsITTCalDropOutliers.
	
	#echo Making Separator_TigressCsITTCalDiff_firstEvent.
	#(cd TigressCsITTCalDiff_firstEvent && make -is clean && make && make -is clean && cd ..)
	#echo DONE: Separator_TigressCsITTCalDiff_firstEvent.
	
	echo Making Separator_CsIPIDER.
	(cd CsIPIDER && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_CsIPIDER.
	
	echo Making Separator_CsIPIDER_Sum.
	(cd CsIPIDER_Sum && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_CsIPIDER_Sum.
	
	echo Making Separator_CsIPID_threshold.
	(cd CsIPID_threshold && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_CsIPID_threshold.
	
	echo Making Separator_CsIDeltaU.
	(cd CsIDeltaU && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_CsIDeltaU.
	
	echo Making Separator_RF.
	(cd RF && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_RF.
	
	echo Making Separator_Fold.
	(cd Fold && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_Fold.
	
	echo Making Separator_TigressPINTTCalDiff.
	(cd TigressPINTTCalDiff && make -is clean && make && make -is clean && cd ..)
	echo DONE: Separator_TigressPINTTCalDiff.

clean:
	(cd AngleBetweenHits            && make -is clean && cd ..)
	(cd TrigBits            && make -is clean && cd ..)
	(cd CsIPos            && make -is clean && cd ..)
	(cd CsIPosSum            && make -is clean && cd ..)
	(cd TigressCsITTCalDiff && make -is clean && cd ..)
	(cd TigressCsITTCalFirstHitDiff && make -is clean && cd ..)
	(cd TigressCsITTCalAnyHitDiff && make -is clean && cd ..)
	(cd TigressCsITTCalFirstHitDiffCentralValue && make -is clean && cd ..)
	(cd TigressTTCalDiff    && make -is clean && cd ..)
	(cd TigressTTCalDiffFirstHit    && make -is clean && cd ..)
	(cd TigressTTCalDiffCentralValue    && make -is clean && cd ..)
	(cd TigressDropCore    && make -is clean && cd ..)
	(cd CsITTCalDiff        && make -is clean && cd ..)
	(cd CsITTCalDiffFirstHit        && make -is clean && cd ..)
	(cd CsITTCalDiffCentralValue        && make -is clean && cd ..)
	(cd CsIPIDER            && make -is clean && cd ..)
	(cd CsIPIDER_Sum        && make -is clean && cd ..)
	(cd CsIDeltaU           && make -is clean && cd ..)
	(cd RF                  && make -is clean && cd ..)
	(cd Fold                && make -is clean && cd ..)
	#(cd TigressCsITTCalDiff_firstEvent	&& make -is clean && cd ..)
	(cd TigressCsITTCalDiffSAFE	&& make -is clean && cd ..)
	(cd TigressPINTTCalDiff     && make -is clean && cd ..)
	rm -f *~
