all:
	echo Making AngleBetweenHits.
	(cd AngleBetweenHits && make -is clean && make && make -is clean && cd ..)
	echo DONE: ANGLEBETWEENHITS.	
	
	echo Making ERaw.
	(cd ERaw && make -is clean && make && make -is clean && cd ..)
	echo DONE: ERAW.
	
	echo Making ERawRing.
	(cd ERawRing && make -is clean && make && make -is clean && cd ..)
	echo DONE: ERAWRING.
	
	echo Making ERawSum.
	(cd ERawSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: ERAWSUM.
	
	echo Making ERawSum_PIDER.
	(cd ERawSum_PIDER && make -is clean && make && make -is clean && cd ..)
	echo DONE: ERAWSUM_PIDER.
	
	echo Making ECal.
	(cd ECal && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECAL.
	
	echo Making ECalSum.
	(cd ECalSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALSUM.
	
	echo Making ECalRing.
	(cd ECalRing && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALRING.
	
	echo Making ECalTotalEventSum.
	(cd ECalTotalEventSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALTotalEventSUM.
	
	echo Making ECal_CsIPIDr.
	(cd ECal_CsIPIDr && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECAL_CSIPIDR.
	
	echo Making ECalSum_PIDr.
	(cd ECalSum_CsIPIDr && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALSUM_PIDR.
	
	echo Making ECalPosSum_PIDr.
	(cd ECalPosSum_CsIPIDr && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALPOSSUM_PIDR.
	
	echo Making ECalParticleSumRunSum_PIDr.
	(cd ECalParticleSumRunSum_CsIPIDr && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALPARTICLESUMRUNSUM_PIDR.
	
	echo Making EECalSum.
	(cd EECalSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: EECALSUM.
	
	echo Making DeltaU.
	(cd DeltaU && make -is clean && make && make -is clean && cd ..)
	echo DONE: DELTAU.
	
	echo Making DeltaUSum.
	(cd DeltaUSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: DELTAUSUM.
	
	echo Making DeltaURingSum.
	(cd DeltaURingSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: DELTAURINGSUM.
	
	echo Making DeltaUSameRingSum.
	(cd DeltaUSameRingSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: DELTAUSAMERINGSUM.

clean:
	(cd AngleBetweenHits 				&& make -is clean && cd ..)
	(cd ERaw 				&& make -is clean && cd ..)
	(cd ERawSum 				&& make -is clean && cd ..)
	(cd ERawSum_PIDER 				&& make -is clean && cd ..)
	(cd ECal 				&& make -is clean && cd ..)
	(cd ECalSum 				&& make -is clean && cd ..)
	(cd ECalRing 				&& make -is clean && cd ..)
	(cd ECalTotalEventSum 				&& make -is clean && cd ..)
	(cd ECal_CsIPIDr 			&& make -is clean && cd ..)
	(cd ECalSum_CsIPIDr 			&& make -is clean && cd ..)
	(cd ECalPosSum_CsIPIDr 			&& make -is clean && cd ..)
	(cd ECalParticleSumRunSum_CsIPIDr	&& make -is clean && cd ..)
	(cd EECalSum 				&& make -is clean && cd ..)
	(cd DeltaU 				&& make -is clean && cd ..)
	(cd DeltaUSum 				&& make -is clean && cd ..)
	(cd DeltaURingSum 				&& make -is clean && cd ..)
	(cd DeltaUSameRingSum 				&& make -is clean && cd ..)

	rm -f *~
