all:
	echo Making Tigress_ECalABSupp.
	(cd ECalABSupp && make -is clean && make && make -is clean && cd ..)
	echo DONE: Tigress_ECalABSupp.
	
	echo Making Tigress_ECalABSuppSeg.
	(cd ECalABSuppSeg && make -is clean && make && make -is clean && cd ..)
	echo DONE: Tigress_ECalABSuppSeg.
	
	echo Making Tigress_ECalABSuppRing.
	(cd ECalABSuppRing && make -is clean && make && make -is clean && cd ..)
	echo DONE: Tigress_ECalABSuppRing.
	
	echo Making Tigress_ECalABSuppRingDopplerCorrected.
	(cd ECalABSuppRingDopplerCorrected && make -is clean && make && make -is clean && cd ..)
	echo DONE: Tigress_ECalABSuppRingDopplerCorrected.
	
	#echo Making Tigress_ECalABSuppTester.
	#(cd ECalABSuppTester && make -is clean && make && make -is clean && cd ..)
	#echo DONE: Tigress_ECalABSuppTester.
	
	echo Making Tigress_ECalABSuppSum.
	(cd ECalABSuppSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: Tigress_ECalABSuppSum.
	
	echo Making Tigress_ECalABSuppRingSum.
	(cd ECalABSuppRingSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: Tigress_ECalABSuppRingSum.
	
	echo Making Tigress_ECalABSuppRing_2SuppGammas.
	(cd ECalABSuppRing_2SuppGammas && make -is clean && make && make -is clean && cd ..)
	echo DONE: Tigress_ECalABSuppRing_2SuppGammas.
	
	echo Making Tigress_ECalABSuppRingSumRingDopplerCorrected.
	(cd ECalABSuppRingSumRingDopplerCorrected && make -is clean && make && make -is clean && cd ..)
	echo DONE: Tigress_ECalABSuppRingSumRingDopplerCorrected.
	
	echo Making Tigress_ECalABSuppRingSumRingDopplerCorrectedEGated.
	(cd ECalABSuppRingSumRingDopplerCorrectedEGated && make -is clean && make && make -is clean && cd ..)
	echo DONE: Tigress_ECalABSuppRingSumRingDopplerCorrectedEGated.
	
	echo Making Tigress_ECalABSuppRingEGated.
	(cd ECalABSuppRingEGated && make -is clean && make && make -is clean && cd ..)
	echo DONE: Tigress_ECalABSuppRingEGated.
		
	echo Making Tigress_ECalABSuppRingSumEGatedFold.
	(cd ECalABSuppRingSumEGatedFold && make -is clean && make && make -is clean && cd ..)
	echo DONE: Tigress_ECalABSuppRingSumEGatedFold.
	
	echo Making Tigress_ECalABSuppRingSumEGatedByRing.
	(cd ECalABSuppRingSumEGatedByRing && make -is clean && make && make -is clean && cd ..)
	echo DONE: Tigress_ECalABSuppRingSumEGatedByRing.
	
	echo Making Tigress_ECalABSuppSumEGated.
	(cd ECalABSuppSumEGated && make -is clean && make && make -is clean && cd ..)
	echo DONE: Tigress_ECalABSuppSumEGated.
	
	echo Making Tigress_ECalABSuppSumEMultiGated.
	(cd ECalABSuppSumEMultiGated && make -is clean && make && make -is clean && cd ..)
	echo DONE: Tigress_ECalABSuppSumEMultiGated.
	
	#echo Making Tigress_ECalABSuppLayerSum.
	#(cd ECalABSuppLayerSum && make -is clean && make && make -is clean && cd ..)
	#echo DONE: Tigress_ECalABSuppLayerSum.
	
	#echo Making Tigress_ECalABSuppLayer.
	#(cd ECalABSuppLayer && make -is clean && make && make -is clean && cd ..)
	#echo DONE: Tigress_ECalABSuppLayer.
	
	#echo Making Tigress_ABSuppPosFoldHP.
	#(cd SuppPosFoldHP && make -is clean && make && make -is clean && cd ..)
	#echo DONE: Tigress_ABSuppPosFoldHP.
	
	#echo Making Tigress_ECalABSupp_OnBGOE.
	#(cd SuppOnBGOELimits && make -is clean && make && make -is clean && cd ..)
	#echo DONE: Tigress_ECalABSupp_OnBGOE.
	
	#echo Making Tigress_ECalABSupp_OnBGOT.
	#(cd SuppOnBGOTLimits && make -is clean && make && make -is clean && cd ..)
	#echo DONE: Tigress_ECalABSupp_OnBGOT.
	
	echo Making Tigress_EECalABSuppSum.
	(cd EECalABSuppSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: Tigress_EECalABSuppSum.
	
	echo Making Tigress_EECalABSuppSumRingDopplerCorrected.
	(cd EECalABSuppSumRingDopplerCorrected && make -is clean && make && make -is clean && cd ..)
	echo DONE: Tigress_EECalABSuppSumRingDopplerCorrected.
	
	#echo Making Tigress_ECalABSupp_OnBGOPresence.
	#(cd SuppOnBGOPresence && make -is clean && make && make -is clean && cd ..)
	#echo DONE: Tigress_ECalABSupp_OnBGOPresence.

clean:
	(cd ECalABSupp               	    && make -is clean && cd ..)
	(cd ECalABSuppSeg               	&& make -is clean && cd ..)
	(cd ECalABSuppRing           	    && make -is clean && cd ..)
	(cd ECalABSuppRingDopplerCorrected     && make -is clean && cd ..)
	#(cd ECalABSuppTester             && make -is clean && cd ..)
	(cd ECalABSuppSum            	    && make -is clean && cd ..)
	(cd ECalABSuppRingSum             && make -is clean && cd ..)
	(cd ECalABSuppRing_2SuppGammas    && make -is clean && cd ..)
	(cd ECalABSuppRingSumRingDopplerCorrected     && make -is clean && cd ..)
	(cd ECalABSuppRingSumRingDopplerCorrectedEGated     && make -is clean && cd ..)
	(cd ECalABSuppRingEGated       && make -is clean && cd ..)
	(cd ECalABSuppRingSumEGatedFold     && make -is clean && cd ..)
	(cd ECalABSuppRingSumEGatedByRing   && make -is clean && cd ..)
	(cd ECalABSuppSumEGated       && make -is clean && cd ..)
	(cd ECalABSuppSumEMultiGated       && make -is clean && cd ..)
	#(cd ECalABSuppLayerSum              && make -is clean && cd ..)
	#(cd SuppPosFoldHP                   && make -is clean && cd ..)
	#(cd SuppOnBGOELimits                && make -is clean && cd ..)
	#(cd SuppOnBGOTLimits                && make -is clean && cd ..)
	#(cd SuppOnBGOPresence               && make -is clean && cd ..)
	(cd EECalABSuppSum        	    && make -is clean && cd ..)
	(cd EECalABSuppSumRingDopplerCorrected    && make -is clean && cd ..)

	rm -f *~
