all:
	echo Making AngleBetweenHits_EGated.
	(cd AngleBetweenHits_EGated && make -is clean && make && make -is clean && cd ..)
	echo DONE: AngleBetweenHits_EGated.
	
	echo Making ECalAB_CsIPIDtr.
	(cd ECalAB_CsIPIDtr && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALAB_CSIPIDTR.
	
	echo Making ECalAB_CsIPIDr.
	(cd ECalAB_CsIPIDr && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALAB_CSIPIDR.
	
	echo Making ECalABSum_CsIPIDr.
	(cd ECalABSum_CsIPIDr && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABSUM_CSIPIDR.
	
	echo Making ECalABSuppSum_CsIPIDr.
	(cd ECalABSuppSum_CsIPIDr && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABSUPPSUM_CSIPIDR.
	
	echo Making ECalABRingSum_CsIPIDr.
	(cd ECalABRingSum_CsIPIDr && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABRINGSUM_CSIPIDR.
	
	echo Making ECalABSuppRingSum_CsIPIDr.
	(cd ECalABSuppRingSum_CsIPIDr && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABSUPPRINGSUM_CSIPIDR.
	
	echo Making ECalABSum_CsIEGate_CsIPIDr.
	(cd ECalABSum_CsIEGate_CsIPIDr && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABSUM_CSIEGATE_CSIPIDR.
	
	echo Making ECalABSuppRingSum_deltaUcut.
	(cd ECalABSuppRingSum_deltaUcut && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABSUPPRINGSUM_DELTAUCUT.
	
	echo Making ECalABSuppCsIRingSum.
	(cd ECalABSuppCsIRingSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABSUPPCSIRINGSUM.
	
	echo Making ECalABSuppCsIRing.
	(cd ECalABSuppCsIRing && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABSUPPCSIRING.
	
	echo Making ECalABSuppDSSum.
	(cd ECalABSuppDSSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABSUPPDSSUM.
	
	echo Making ECalABSuppDSSumEGated.
	(cd ECalABSuppDSSumEGated && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABSUPPDSSUMEGATED.
	
	echo Making ECalABSuppSumTree.
	(cd ECalABSuppSumTree && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABSUPPSUMTREE.
	
	echo Making deltaU_ECalCut.
	(cd deltaU_ECalCut && make -is clean && make && make -is clean && cd ..)
	echo DONE: DELTAU_ECALCUT.
	
	echo Making ECalABRing_CsIEGate.
	(cd  ECalABRing_CsIEGate && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABRING_CSIEGATE.
	
	echo Making ECalABRingSum_CsIEGate.
	(cd  ECalABRingSum_CsIEGate && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECALABRINGSUM_CSIEGATE.
	
	echo Making CsIECalSum_TigEGate.
	(cd  CsIECalSum_TigEGate && make -is clean && make && make -is clean && cd ..)
	echo DONE: CSIECALSUM_TIGEGATE.
	
	echo Making CsIECal_TigEGate.
	(cd  CsIECal_TigEGate && make -is clean && make && make -is clean && cd ..)
	echo DONE: CSIECAL_TIGEGATE.
	
	echo Making EE_Plunger.
	(cd  EE_Plunger && make -is clean && make && make -is clean && cd ..)
	echo DONE: EE_PLUNGER.
	
	echo Making EE_PlungerSum.
	(cd  EE_PlungerSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: EE_PLUNGERSUM.
	
	echo Making EECal.
	(cd  EECal && make -is clean && make && make -is clean && cd ..)
	echo DONE: EECAL.
	
	echo Making ECosThetaCalABSuppSum.
	(cd  ECosThetaCalABSuppSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECosThetaCalABSuppSum.
	
	echo Making ECosThetaCalABSuppSum_LineCut.
	(cd  ECosThetaCalABSuppSum_LineCut && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECosThetaCalABSuppSum_LineCut.
	
	echo Making ECosThetaCalABSuppSum_LineCutThreshold.
	(cd  ECosThetaCalABSuppSum_LineCutThreshold && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECosThetaCalABSuppSum_LineCutThreshold.
	
	echo Making ECosThetaCalABSuppSum_Rotated.
	(cd  ECosThetaCalABSuppSum_Rotated && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECosThetaCalABSuppSum_Rotated.
	
	echo Making ECosThetaCalABSuppSum_RotatedCosThetaGate.
	(cd  ECosThetaCalABSuppSum_RotatedCosThetaGate && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECosThetaCalABSuppSum_RotatedCosThetaGate.
	
	echo Making ECalABSuppDSReconstructed.
	(cd  ECalABSuppDSReconstructed && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppDSReconstructed.
	
	echo Making ECalABSuppDSReconstructedSum.
	(cd  ECalABSuppDSReconstructedSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppDSReconstructedSum.
	
	echo Making ECalABSuppDSReconstructedSumEGated.
	(cd  ECalABSuppDSReconstructedSumEGated && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppDSReconstructedSumEGated.
	
	echo Making ECalABSuppDSReconstructedSumEGatedPID.
	(cd  ECalABSuppDSReconstructedSumEGatedPID && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppDSReconstructedSumEGatedPID.
	
	echo Making ECalABSuppDSReconstructedSumEMultiGatedPID.
	(cd  ECalABSuppDSReconstructedSumEMultiGatedPID && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppDSReconstructedSumEMultiGatedPID.
	
	echo Making ECalABSuppSumDSEGated.
	(cd  ECalABSuppSumDSEGated && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppSumDSEGated.
	
	echo Making ECalABSuppSumDSEGatedPID.
	(cd  ECalABSuppSumDSEGatedPID && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppSumDSEGatedPID.
	
	echo Making ECalABSuppSumDSEGated_Group.
	(cd  ECalABSuppSumDSEGated_Group && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppSumDSEGated_Group.
	
	echo Making ECalABSuppSumDSEGated_GroupPID.
	(cd  ECalABSuppSumDSEGated_GroupPID && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppSumDSEGated_GroupPID.
	
	echo Making DSECalABSuppSumEGated.
	(cd  DSECalABSuppSumEGated && make -is clean && make && make -is clean && cd ..)
	echo DONE: DSECalABSuppSumEGated.
	
	echo Making DSECalABSuppSumEGatedPID.
	(cd  DSECalABSuppSumEGatedPID && make -is clean && make && make -is clean && cd ..)
	echo DONE: DSECalABSuppSumEGatedPID.
	
	echo Making ECalABSuppSegDSReconstructedSum.
	(cd  ECalABSuppSegDSReconstructedSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppSegDSReconstructedSum.
	
	echo Making ECosThetaCalABSuppSum_Sheared.
	(cd  ECosThetaCalABSuppSum_Sheared && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECosThetaCalABSuppSum_Sheared.
	
	echo Making EECalABSuppSumDSReconstructedSum.
	(cd  EECalABSuppSumDSReconstructedSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: EECalABSuppSumDSReconstructedSum.
	
	echo Making EECalABSuppSumDSReconstructedSumPID.
	(cd  EECalABSuppSumDSReconstructedSumPID && make -is clean && make && make -is clean && cd ..)
	echo DONE: EECalABSuppSumDSReconstructedSumPID.
	
	echo Making FusEvap_ResE.
	(cd  FusEvap_ResE && make -is clean && make && make -is clean && cd ..)
	echo DONE: FusEvap_ResE.
	
	echo Making ECalABGroup.
	(cd  ECalABGroup && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABGroup.
	
	echo Making ECalABGroupSum.
	(cd  ECalABGroupSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABGroupSum.
	
	echo Making ECalABSuppGroup.
	(cd  ECalABSuppGroup && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppGroup.
	
	echo Making ECalABSuppGroupSum.
	(cd  ECalABSuppGroupSum && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppGroupSum.
	
	echo Making ECalABSuppSumEGated_Group.
	(cd  ECalABSuppSumEGated_Group && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppSumEGated_Group.
	
	echo Making ECalABSuppGroupSumEGatedByGroup.
	(cd  ECalABSuppGroupSumEGatedByGroup && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppGroupSumEGatedByGroup.
	
	echo Making ECalABSuppDSReconstructedSumEGatedPIDSumCorr.
	(cd  ECalABSuppDSReconstructedSumEGatedPIDSumCorr && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppDSReconstructedSumEGatedPIDSumCorr.
	
	echo Making ECalABSuppDSReconstructedSumEGatedPID180.
	(cd  ECalABSuppDSReconstructedSumEGatedPID180 && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppDSReconstructedSumEGatedPID180.
	
	echo Making ECalABSuppDSReconstructedSumEGatedPID180_2ndGate.
	(cd  ECalABSuppDSReconstructedSumEGatedPID180_2ndGate && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppDSReconstructedSumEGatedPID180_2ndGate.
	
	echo Making ECalABSuppDSReconstructedSumEGatedPIDAngCorr.
	(cd  ECalABSuppDSReconstructedSumEGatedPIDAngCorr && make -is clean && make && make -is clean && cd ..)
	echo DONE: ECalABSuppDSReconstructedSumEGatedPIDAngCorr.


clean:
	(cd AngleBetweenHits_EGated            && make -is clean && cd ..)
	(cd ECalAB_CsIPIDtr                    && make -is clean && cd ..)
	(cd ECalAB_CsIPIDr                     && make -is clean && cd ..)
	(cd ECalABSum_CsIPIDr                  && make -is clean && cd ..)
	(cd ECalABSuppSum_CsIPIDr              && make -is clean && cd ..)
	(cd ECalABRingSum_CsIPIDr              && make -is clean && cd ..)
	(cd ECalABSuppRingSum_CsIPIDr          && make -is clean && cd ..)
	(cd ECalABSum_CsIEGate_CsIPIDr         && make -is clean && cd ..)
	(cd ECalABSuppRingSum_deltaUcut        && make -is clean && cd ..)
	(cd ECalABSuppCsIRing                  && make -is clean && cd ..)
	(cd ECalABSuppCsIRingSum               && make -is clean && cd ..)
	(cd ECalABSuppDSSum                    && make -is clean && cd ..)
	(cd ECalABSuppDSSumEGated              && make -is clean && cd ..)
	(cd ECalABSuppSumTree                  && make -is clean && cd ..)
	(cd deltaU_ECalCut                     && make -is clean && cd ..)
	(cd ECalABRing_CsIEGate                && make -is clean && cd ..)
	(cd ECalABRingSum_CsIEGate             && make -is clean && cd ..)
	(cd CsIECal_TigEGate                   && make -is clean && cd ..)
	(cd CsIECalSum_TigEGate                && make -is clean && cd ..)
	(cd EE_Plunger                         && make -is clean && cd ..)
	(cd EE_PlungerSum                      && make -is clean && cd ..)
	(cd EECal                              && make -is clean && cd ..)
	(cd ECosThetaCalABSuppSum              && make -is clean && cd ..)
	(cd ECosThetaCalABSuppSum_LineCut      && make -is clean && cd ..)
	(cd ECosThetaCalABSuppSum_LineCutThreshold     && make -is clean && cd ..)
	(cd ECosThetaCalABSuppSum_Rotated       && make -is clean && cd ..)
	(cd ECosThetaCalABSuppSum_RotatedCosThetaGate  && make -is clean && cd ..)
	(cd ECalABSuppDSReconstructed  && make -is clean && cd ..)
	(cd ECalABSuppDSReconstructedSum  && make -is clean && cd ..)
	(cd ECalABSuppDSReconstructedSumEGated  && make -is clean && cd ..)
	(cd ECalABSuppDSReconstructedSumEGatedPID  && make -is clean && cd ..)
	(cd ECalABSuppDSReconstructedSumEMultiGatedPID  && make -is clean && cd ..)
	(cd ECalABSuppSumDSEGated  && make -is clean && cd ..)
	(cd ECalABSuppSumDSEGatedPID  && make -is clean && cd ..)
	(cd ECalABSuppSumDSEGated_Group  && make -is clean && cd ..)
	(cd ECalABSuppSumDSEGated_GroupPID  && make -is clean && cd ..)
	(cd DSECalABSuppSumEGated  && make -is clean && cd ..)
	(cd DSECalABSuppSumEGatedPID  && make -is clean && cd ..)
	(cd ECalABSuppSegDSReconstructedSum  && make -is clean && cd ..)
	(cd ECosThetaCalABSuppSum_Sheared  && make -is clean && cd ..)
	(cd EECalABSuppSumDSReconstructedSum  && make -is clean && cd ..)
	(cd EECalABSuppSumDSReconstructedSumPID  && make -is clean && cd ..)
	(cd FusEvap_ResE  && make -is clean && cd ..)
	(cd ECalABGroup              && make -is clean && cd ..)
	(cd ECalABGroupSum              && make -is clean && cd ..)
	(cd ECalABSuppGroup              && make -is clean && cd ..)
	(cd ECalABSuppGroupSum              && make -is clean && cd ..)
	(cd ECalABSuppSumEGated_Group             && make -is clean && cd ..)
	(cd ECalABSuppGroupSumEGatedByGroup       && make -is clean && cd ..)
	(cd ECalABSuppDSReconstructedSumEGatedPIDSumCorr       && make -is clean && cd ..)
	(cd ECalABSuppDSReconstructedSumEGatedPID180       && make -is clean && cd ..)
	(cd ECalABSuppDSReconstructedSumEGatedPID180_2ndGate       && make -is clean && cd ..)
	(cd ECalABSuppDSReconstructedSumEGatedPIDAngCorr       && make -is clean && cd ..)

	rm -f *~
